-- CreateEnum
CREATE TYPE "WordCategory" AS ENUM ('BASICS', 'GREETINGS', 'PEOPLE_FAMILY', 'NUMBERS_COUNTING', 'TIME_DATE', 'FOOD_DRINK', 'RESTAURANT_DINING', 'SHOPPING', 'TRAVEL_TRANSPORTATION', 'DIRECTIONS_PLACES', 'HOME_DAILY_LIFE', 'WORK_SCHOOL', 'HEALTH_BODY', 'WEATHER_NATURE', 'EMOTIONS_FEELINGS', 'DESCRIPTIONS_COLORS', 'ANIMALS', 'HOBBIES_ENTERTAINMENT', 'TECHNOLOGY_COMMUNICATION', 'MONEY_FINANCE', 'CLOTHING', 'OTHER');

-- AlterTable
ALTER TABLE "Word" ADD COLUMN     "category" "WordCategory" NOT NULL DEFAULT 'OTHER';

-- CreateIndex
CREATE INDEX "Word_languageCode_category_idx" ON "Word"("languageCode", "category");
