// Question bank + grading for the Korean "Symbols" quiz.
//
// One QuizItem is one (letter, position) concept - e.g. "ㅅ at the end of a syllable" is a different
// item from "ㅅ at the start", because it sounds different (t vs s). Each item has several variants
// (different English words) so repeated quizzes don't feel identical. Progress is tracked per item.
//
// Accuracy bar is the same as src/lib/hangul.ts: nothing here is generated by an LLM at runtime, and
// the sound claims follow the same deliberate calls (plain / aspirated / tense stops via go / kite /
// sky, ㅓ = "u in cup", ㅅ -> "sh" before ㅣ, finals neutralize to seven sounds, ㅐ/ㅔ told apart by
// their Revised Romanization code even though modern speech merges them).

import { HANGUL_SYMBOLS } from "./hangul";
import { blankedWord, fullWord } from "./hangulBlocks";
import { explainWrong } from "./hangulMisconceptions";
import type { Grade, QuizDefinition, QuizItem as BaseItem, QuizVariant as BaseVariant } from "./quizTypes";
export { blankedWord, decomposeBlock, fullWord } from "./hangulBlocks";
export type { Grade } from "./quizTypes";

export type QuizPosition = "initial" | "medial" | "final" | "vowel";

export const POSITION_LABEL: Record<QuizPosition, string> = {
  initial: "Start of a syllable",
  medial: "Between vowels",
  final: "End of a syllable",
  vowel: "Vowel",
};

export type QuizVariant = BaseVariant & {
  // Letters that share a sound (the finals ㄷㅅㅈㅊㅌㅆㅎ all end in t; ㅙ ㅚ ㅞ all say "weh") need a
  // Korean word to pin down which one is meant: `before + block + after`, with one letter of the
  // block blanked (its final by default, or its vowel).
  ko?: { before?: string; block: string; after?: string; blank?: "final" | "vowel"; gloss: string };
};

// id: "i:ㄱ" initial, "m:ㄱ" medial, "f:ㄱ" final, "v:ㅏ" vowel. `answer` is the one canonical jamo
// and `code` the Revised Romanization shown with the question.
export type QuizItem = Omit<BaseItem, "variants"> & {
  position: QuizPosition;
  variants: QuizVariant[];
};

// --- Authoring helpers -------------------------------------------------------------------------

type V = [text: string, extra?: Omit<QuizVariant, "text" | "context">];

const variants = (list: V[]): QuizVariant[] => list.map(([text, extra]) => ({ text, ...extra }));

const initial = (answer: string, code: string, note: string, list: V[]): QuizItem => ({
  id: `i:${answer}`,
  answer,
  position: "initial",
  group: POSITION_LABEL["initial"],
  code,
  note,
  variants: variants(list),
});

const medial = (answer: string, code: string, note: string, list: V[]): QuizItem => ({
  id: `m:${answer}`,
  answer,
  position: "medial",
  group: POSITION_LABEL["medial"],
  code,
  note,
  variants: variants(list),
});

const final = (answer: string, code: string, note: string, list: V[]): QuizItem => ({
  id: `f:${answer}`,
  answer,
  position: "final",
  group: POSITION_LABEL["final"],
  code,
  note,
  variants: variants(list),
});

const vowel = (answer: string, code: string, note: string, list: V[]): QuizItem => ({
  id: `v:${answer}`,
  answer,
  position: "vowel",
  group: POSITION_LABEL["vowel"],
  code,
  note,
  variants: variants(list),
});

// Korean-word context for a final-position variant.
const ko = (block: string, gloss: string, before = "", after = ""): { ko: NonNullable<QuizVariant["ko"]> } => ({
  ko: { before, block, after, gloss },
});

// Same, but the block's vowel is the blank.
const vko = (block: string, gloss: string, before = "", after = ""): { ko: NonNullable<QuizVariant["ko"]> } => ({
  ko: { before, block, after, blank: "vowel", gloss },
});

// --- The bank ----------------------------------------------------------------------------------

const INITIALS: QuizItem[] = [
  initial("ㄱ", "g", "At the start of a syllable ㄱ is a soft g with little air (Revised Romanization writes g). ㅋ is the k with a puff of air and ㄲ the tight k - different letters.", [
    ["**g**o"], ["**g**ame"], ["**g**ive"],
  ]),
  initial("ㄲ", "kk", "The tense k: no puff of air and a tight throat, exactly like the k in English \"sky\" (after an s, English k is unaspirated). ㄱ is softer, ㅋ is puffier.", [
    ["s**k**y"], ["s**k**ate"], ["s**k**i"],
  ]),
  initial("ㄴ", "n", "ㄴ is an ordinary n at the start of a syllable.", [
    ["**n**o"], ["**n**ice"], ["**n**ame"],
  ]),
  initial("ㄷ", "d", "At the start of a syllable ㄷ is a soft d with little air. ㅌ is the t with a puff of air and ㄸ the tight t.", [
    ["**d**og"], ["**d**ay"], ["**d**oor"],
  ]),
  initial("ㄸ", "tt", "The tense t: no puff of air and a tight throat, like the t in English \"stop\". ㄷ is softer, ㅌ is puffier.", [
    ["s**t**op"], ["s**t**ar"], ["s**t**ay"],
  ]),
  initial("ㄹ", "r", "At the start of a syllable (and between vowels) ㄹ is a quick tap of the tongue - the \"tt\" of American \"butter\" - not an English r. At the END of a syllable it is an l.", [
    ["bu**tt**er"], ["la**dd**er"], ["wa**t**er"],
  ]),
  initial("ㅁ", "m", "ㅁ is an ordinary m at the start of a syllable.", [
    ["**m**om"], ["**m**oon"], ["**m**ap"],
  ]),
  initial("ㅂ", "b", "At the start of a syllable ㅂ is a soft b with little air. ㅍ is the p with a puff of air and ㅃ the tight p.", [
    ["**b**oy"], ["**b**ig"], ["**b**ook"],
  ]),
  initial("ㅃ", "pp", "The tense p: no puff of air and a tight throat, like the p in English \"spy\". ㅂ is softer, ㅍ is puffier.", [
    ["s**p**y"], ["s**p**ot"], ["s**p**ort"],
  ]),
  initial("ㅅ", "s", "At the start of a syllable ㅅ is s. Before ㅣ and the y-vowels (ㅑ ㅕ ㅛ ㅠ) it softens to sh (시 = shee) - but it is still ㅅ. At the END of a syllable it is a t, not an s.", [
    ["**s**un"], ["**s**ong"],
    ["**sh**eep", { code: "s", note: "Before ㅣ the ㅅ sounds like sh: 시 is pronounced \"shee\", though Revised Romanization writes it si." }],
  ]),
  initial("ㅆ", "ss", "The tense s: a tighter, sharper hiss than ㅅ, with a tight throat. English has no exact match - hold the hiss of \"hiss\". Before ㅣ it becomes a tense sh (씨).", [
    ["hi**ss**ing"], ["mi**ss**ing"], ["ki**ss**ing"],
  ]),
  initial("ㅇ", "(silent)", "Every Korean syllable is written with a consonant letter first. When the syllable starts with a vowel sound, the silent placeholder ㅇ goes there and makes no sound at all (아 = \"ah\"). At the END of a syllable the same letter is ng.", [
    ["ah", { prompt: "Every Korean syllable begins with a consonant letter. Which silent placeholder goes first when the syllable starts with a vowel sound, like \"ah\"?" }],
    ["oh", { prompt: "Every Korean syllable begins with a consonant letter. Which silent placeholder goes first when the syllable starts with a vowel sound, like \"oh\"?" }],
    ["ee", { prompt: "Every Korean syllable begins with a consonant letter. Which silent placeholder goes first when the syllable starts with a vowel sound, like \"ee\"?" }],
  ]),
  initial("ㅈ", "j", "At the start of a syllable ㅈ is a soft j with little air (between English j and ch). ㅊ is the ch with a puff of air and ㅉ the tight j.", [
    ["**j**ump"], ["**j**ust"], ["**j**ob"],
  ]),
  initial("ㅉ", "jj", "The tense j: no puff of air, throat tight, clipped. English has no exact match - say \"jeep\" tight and short. ㅈ is softer, ㅊ is puffier.", [
    ["**j**eep, said tight and clipped"], ["**j**ump, said tight and clipped"],
  ]),
  initial("ㅊ", "ch", "ㅊ is ch with a strong puff of air - the aspirated partner of ㅈ.", [
    ["**ch**urch"], ["**ch**ip"], ["**ch**air"],
  ]),
  initial("ㅋ", "k", "ㅋ is k with a strong puff of air, like the k in \"kite\" - the aspirated partner of ㄱ.", [
    ["**k**ite"], ["**k**ey"], ["**c**at"],
  ]),
  initial("ㅌ", "t", "ㅌ is t with a strong puff of air, like the t in \"top\" - the aspirated partner of ㄷ.", [
    ["**t**op"], ["**t**en"], ["**t**able"],
  ]),
  initial("ㅍ", "p", "ㅍ is p with a strong puff of air, like the p in \"pie\" - the aspirated partner of ㅂ.", [
    ["**p**ie"], ["**p**en"], ["**p**ark"],
  ]),
  initial("ㅎ", "h", "ㅎ is an ordinary h at the start of a syllable (it softens or disappears between vowels).", [
    ["**h**at"], ["**h**ome"], ["**h**i"],
  ]),
];

// Between two vowels the soft (plain) stops become fully voiced - the same letter, a different
// sound from word-initially. Aspirated and tense stops don't change.
const MEDIALS: QuizItem[] = [
  medial("ㄱ", "g", "Between two vowels ㄱ is a clear, voiced g (아가 = aga). At the start of a word it is closer to a g/k in between.", [
    ["a**g**o"], ["a**g**ain"], ["ea**g**er"],
  ]),
  medial("ㄷ", "d", "Between two vowels ㄷ is a clear, voiced d (아다 = ada). At the start of a word it is a softer, lower-air d.", [
    ["i**d**ea"], ["a**d**ore"],
  ]),
  medial("ㅂ", "b", "Between two vowels ㅂ is a clear, voiced b (아바 = aba). At the start of a word it is a softer, lower-air b.", [
    ["a**b**ove"], ["a**b**out"],
  ]),
  medial("ㅈ", "j", "Between two vowels ㅈ is a clear, voiced j (아자 = aja). At the start of a word it is a softer, lower-air j.", [
    ["a**j**ar"], ["ma**j**or"],
  ]),
];

const NEUTRAL_T = "At the START of a syllable this letter has its own sound, but at the END of a syllable it collapses to an unreleased t - along with ㄷ ㅅ ㅈ ㅊ ㅌ ㅆ ㅎ. They sound identical there, so which one a word uses has to be learned with the word.";
const NEUTRAL_K = "At the END of a syllable ㄱ ㅋ ㄲ all collapse to the same unreleased k, so which one a word uses has to be learned with the word.";
const NEUTRAL_P = "At the END of a syllable ㅂ and ㅍ both collapse to the same unreleased p, so which one a word uses has to be learned with the word.";

const FINALS: QuizItem[] = [
  final("ㄱ", "k", `${NEUTRAL_K} ㄱ is the plain, most common spelling of this sound. At the start of a syllable it is g.`, [
    ["boo**k**", ko("책", "book", "", "")],
    ["ba**ck**", ko("국", "soup")],
    ["pi**ck**", ko("약", "medicine")],
  ]),
  final("ㅋ", "k", `${NEUTRAL_K} ㅋ keeps its puff of air only when a vowel follows; at the end of a syllable nothing is released.`, [
    ["boo**k**", ko("엌", "kitchen", "부")],
    ["ba**ck**", ko("읔", "the letter ㅋ's own name, 키읔", "키")],
  ]),
  final("ㄲ", "k", `${NEUTRAL_K} ㄲ at the end is still just an unreleased k - the tightness only shows up when a vowel follows.`, [
    ["ba**ck**", ko("밖", "outside")],
    ["boo**k**", ko("낚", "fishing", "", "시")],
  ]),
  final("ㄴ", "n", "ㄴ is n at both the start and the end of a syllable - it doesn't change.", [
    ["su**n**"], ["mea**n**"], ["ru**n**"],
  ]),
  final("ㄷ", "t", NEUTRAL_T, [
    ["ca**t**", ko("곧", "soon")],
    ["hea**t**", ko("듣", "to listen", "", "다")],
  ]),
  final("ㅅ", "t", `${NEUTRAL_T} Even the English word "good" turns into 굿 (ㄱ+ㅜ+ㅅ), with a ㅅ that is pronounced t.`, [
    ["goo**d**", ko("굿", "\"good\" (the English loanword)")],
    ["ca**t**", ko("옷", "clothes")],
    ["hea**t**", ko("웃", "to laugh", "", "다")],
  ]),
  final("ㅈ", "t", NEUTRAL_T, [
    ["ca**t**", ko("낮", "daytime")],
    ["hea**t**", ko("젖", "breast milk")],
    ["goo**d**", ko("맞", "to be correct", "", "다")],
  ]),
  final("ㅊ", "t", NEUTRAL_T, [
    ["ca**t**", ko("꽃", "flower")],
    ["hea**t**", ko("빛", "light")],
  ]),
  final("ㅌ", "t", NEUTRAL_T, [
    ["ca**t**", ko("밭", "field")],
    ["hea**t**", ko("끝", "end")],
    ["goo**d**", ko("같", "to be the same", "", "다")],
  ]),
  final("ㅆ", "t", `${NEUTRAL_T} ㅆ is the past-tense ending (갔다, 했다), so this one shows up constantly.`, [
    ["ca**t**", ko("있", "to exist / to have", "", "다")],
    ["hea**t**", ko("갔", "went", "", "다")],
    ["goo**d**", ko("했", "did", "", "다")],
  ]),
  final("ㅎ", "t", `${NEUTRAL_T} ㅎ at the end is rare and usually silent or merges into the next consonant (좋다 = jota); it only sounds like t when the word ends right there.`, [
    ["hea**t**", ko("읗", "the letter ㅎ's own name, 히읗", "히")],
  ]),
  final("ㄹ", "l", "ㄹ at the end of a syllable is an l (물 = mul). At the START of a syllable, or between vowels, it is a quick tap instead.", [
    ["fee**l**"], ["ba**ll**"], ["wa**ll**"],
  ]),
  final("ㅁ", "m", "ㅁ is m at both the start and the end of a syllable - it doesn't change.", [
    ["hu**m**"], ["tea**m**"], ["ho**m**e"],
  ]),
  final("ㅂ", "p", `${NEUTRAL_P} ㅂ is the plain spelling; at the start of a syllable it is b.`, [
    ["cu**p**", ko("밥", "cooked rice")],
    ["ma**p**", ko("집", "house")],
    ["sto**p**", ko("입", "mouth")],
  ]),
  final("ㅍ", "p", `${NEUTRAL_P} ㅍ keeps its puff of air only when a vowel follows; at the end of a syllable nothing is released.`, [
    ["cu**p**", ko("앞", "front")],
    ["ma**p**", ko("숲", "forest")],
    ["sto**p**", ko("옆", "beside")],
  ]),
  final("ㅇ", "ng", "At the END of a syllable ㅇ is ng, as in \"sing\" (강 = gang). At the START of a syllable the same letter is silent. Korean never starts a syllable with ng.", [
    ["si**ng**"], ["so**ng**"], ["ki**ng**"],
  ]),
];

const VOWEL_ITEMS: QuizItem[] = [
  vowel("ㅏ", "a", "ㅏ is an open \"ah\", like the a in \"father\".", [["f**a**ther"], ["sp**a**"], ["p**a**lm"]]),
  vowel("ㅑ", "ya", "ㅑ is ㅏ with a y-glide in front: \"yah\".", [["**ya**rd"], ["**Ya**hoo"]]),
  vowel("ㅓ", "eo", "ㅓ is \"uh\", like the u in \"cup\": mouth open, lips unrounded. It is not \"oh\" and not the rounded \"aw\" of \"saw\" - that is why it is romanized eo.", [["c**u**p"], ["s**u**n"], ["b**u**t"]]),
  vowel("ㅕ", "yeo", "ㅕ is ㅓ with a y-glide in front: \"yuh\".", [["**yu**ck"], ["**yu**mmy"]]),
  vowel("ㅗ", "o", "ㅗ is a pure \"oh\" with the lips rounded and held - no \"w\" tail on the end like the English \"go\" has.", [["g**o**"], ["b**o**ne"], ["**o**kay"]]),
  vowel("ㅛ", "yo", "ㅛ is ㅗ with a y-glide in front: \"yoh\".", [["**yo**ga"], ["**yo**yo"], ["**yo**ke"]]),
  vowel("ㅜ", "u", "ㅜ is \"oo\" with the lips rounded, like the oo in \"moon\".", [["m**oo**n"], ["f**oo**d"], ["bl**ue**"]]),
  vowel("ㅠ", "yu", "ㅠ is ㅜ with a y-glide in front: \"yoo\", like the English word \"you\".", [["**you**"], ["**u**se"], ["m**u**le"]]),
  vowel("ㅡ", "eu", "ㅡ has no English equivalent: say the \"oo\" of \"good\" but spread your lips flat as if smiling.", [["g**oo**d, with the lips spread flat"], ["t**oo**k, with the lips spread flat"]]),
  vowel("ㅣ", "i", "ㅣ is \"ee\", like the ee in \"see\".", [["s**ee**"], ["m**ee**t"], ["b**ee**"]]),
  vowel(
    "ㅐ",
    "ae",
    "ㅐ is romanized ae. Historically it was the a of \"cat\", but modern speakers say it exactly like ㅔ (the e of \"bed\"), so the romanized code is what tells the two letters apart.",
    [["b**a**t"], ["h**a**t"], ["c**a**t"]],
  ),
  vowel("ㅒ", "yae", "ㅒ is ㅐ with a y-glide in front. It is rare, and in modern speech sounds the same as ㅖ.", [["**ya**m"], ["**ya**k"]]),
  vowel(
    "ㅔ",
    "e",
    "ㅔ is romanized e, the e of \"bed\". Modern speakers pronounce it identically to ㅐ, so the romanized code is what tells the two letters apart.",
    [["b**e**d"], ["p**e**n"], ["m**e**t"]],
  ),
  vowel(
    "ㅖ",
    "ye",
    "ㅖ is \"yeh\". After a consonant it loses the y-glide and sounds like ㅔ (계 = geh, 혜 = heh). It sounds the same as ㅒ in modern speech.",
    [["**ye**s"], ["**ye**ll"], ["**ye**t"]],
  ),
  vowel("ㅘ", "wa", "ㅘ is ㅗ + ㅏ blended quickly: \"wah\". Type it as ㅗ then ㅏ.", [
    ["**wa**ffle", { note: "Korean spells English \"waffle\" 와플." }],
    ["**wa**sabi", { note: "Korean spells it 와사비." }],
    ["**wa**nd", { note: "Korean spells English \"wand\" 완드." }],
  ]),
  vowel(
    "ㅙ",
    "wae",
    "ㅙ is romanized wae (ㅗ + ㅐ). In modern speech ㅙ, ㅚ and ㅞ all sound the same (\"weh\"), so English can't tell you which one a word uses - the Korean word does. English \"we\" itself is spelled with ㅞ.",
    [
      ["**weh**", vko("왜", "why")],
      ["**weh**", vko("돼", "pig", "", "지")],
      ["**weh**", vko("꽤", "quite, fairly")],
    ],
  ),
  vowel(
    "ㅚ",
    "oe",
    "ㅚ is romanized oe (ㅗ + ㅣ). Historically a rounded \"ö\", it now sounds like ㅙ and ㅞ (\"weh\"), so English can't tell you which one a word uses - the Korean word does. English \"we\" itself is spelled with ㅞ.",
    [
      ["**weh**", vko("외", "foreign country", "", "국")],
      ["**weh**", vko("회", "company", "", "사")],
      ["**weh**", vko("최", "the best", "", "고")],
    ],
  ),
  vowel("ㅝ", "wo", "ㅝ is ㅜ + ㅓ blended quickly: \"wuh\". Type it as ㅜ then ㅓ.", [
    ["**wo**n", { note: "Korean spells the currency \"won\" 원." }],
    ["**wo**nder", { note: "Korean spells English \"wonder\" 원더." }],
    ["**wa**ter", { note: "Korean spells English \"water\" 워터, with ㅝ - not ㅘ." }],
    ["**wa**tch", { note: "Korean spells English \"watch\" 워치, with ㅝ - not ㅘ." }],
  ]),
  vowel(
    "ㅞ",
    "we",
    "ㅞ is romanized we (ㅜ + ㅔ). In modern speech ㅞ, ㅙ and ㅚ all sound the same (\"weh\"). English \"we\" is spelled with ㅞ in Korean: 웹 (web), 웨스트 (west), 웰 (well).",
    [["**we**t"], ["**we**b"], ["**we**st"], ["**we**ll"]],
  ),
  vowel("ㅟ", "wi", "ㅟ is ㅜ + ㅣ blended quickly: \"wee\".", [["**wee**k"], ["**wee**p"]]),
  vowel(
    "ㅢ",
    "ui",
    "ㅢ is ㅡ + ㅣ blended quickly (\"eu-ee\"). It has three readings: that blend at the start of a word, \"eh\" as the possessive particle 의, and just \"ee\" after a consonant (희, 늬).",
    [["**eu-ee**, said quickly: \"g**oo**\" + \"**ee**\" with flat lips"]],
  ),
];

export const QUIZ_ITEMS: QuizItem[] = [...INITIALS, ...MEDIALS, ...FINALS, ...VOWEL_ITEMS];

const ITEM_BY_ID = new Map(QUIZ_ITEMS.map((item) => [item.id, item]));

export function itemById(id: string): QuizItem | undefined {
  return ITEM_BY_ID.get(id);
}

export const DEFAULT_PROMPT = "Write the Hangul letter for the bold sound.";

export function variantCode(item: QuizItem, variantIndex: number): string {
  return item.variants[variantIndex]?.code ?? item.code;
}

// --- Grading -----------------------------------------------------------------------------------

// Compatibility jamo (what phone keyboards and IMEs produce) keyed by the conjoining jamo that
// NFKD turns them into, so input in either block compares equal.
const COMPAT_JAMO = new Set(HANGUL_SYMBOLS.map((s) => s.jamo));
const CONJOINING_TO_COMPAT = new Map<string, string>(
  [...COMPAT_JAMO].map((jamo) => [jamo.normalize("NFKD"), jamo]),
);

const VOWEL_JAMO = new Set(
  HANGUL_SYMBOLS.filter((s) => s.kind === "Vowel" || s.kind === "Compound vowel").map((s) => s.jamo),
);

// Keystroke pairs that make one letter.
const FUSED_LETTERS = new Map<string, string>([
  ["ㅗㅏ", "ㅘ"], ["ㅗㅐ", "ㅙ"], ["ㅗㅣ", "ㅚ"], ["ㅜㅓ", "ㅝ"], ["ㅜㅔ", "ㅞ"], ["ㅜㅣ", "ㅟ"], ["ㅡㅣ", "ㅢ"],
  ["ㄱㄱ", "ㄲ"], ["ㄷㄷ", "ㄸ"], ["ㅂㅂ", "ㅃ"], ["ㅅㅅ", "ㅆ"], ["ㅈㅈ", "ㅉ"],
]);

function normalizeGiven(input: string): { jamo: string } | { error: string } {
  const text = input.trim();
  if (!text) return { error: "Type the Hangul letter first - or tap one on the keypad." };
  const chars = [...text];
  if (chars.length > 1) {
    // Some keyboards/IMEs don't fuse a lone vowel pair or a doubled consonant into one letter, so
    // accept the keystrokes that make up a compound letter: ㅗ ㅏ -> ㅘ, ㅅ ㅅ -> ㅆ.
    const fused = chars.length === 2 ? FUSED_LETTERS.get(chars.join("")) : undefined;
    if (fused) return { jamo: fused };
    if (chars.length === 2 && chars.every((c) => VOWEL_JAMO.has(c))) {
      return {
        error: `${chars.join(" + ")} doesn't combine into a Hangul vowel. The "wa" sound is ㅘ (ㅗ + ㅏ), "wuh" is ㅝ (ㅜ + ㅓ), "weh" is ㅞ (ㅜ + ㅔ). The keypad has every vowel as one key.`,
      };
    }
    return { error: "Type just one letter - not a whole syllable or word." };
  }
  const ch = chars[0];
  const code = ch.codePointAt(0) ?? 0;
  if (code >= 0xac00 && code <= 0xd7a3) {
    return { error: `${ch} is a whole syllable block. This quiz asks for a single letter - one consonant or one vowel.` };
  }
  const compat = COMPAT_JAMO.has(ch) ? ch : (CONJOINING_TO_COMPAT.get(ch) ?? CONJOINING_TO_COMPAT.get(ch.normalize("NFKD")));
  if (compat) return { jamo: compat };
  if (/^[a-z]$/i.test(ch)) {
    return { error: "That's a Latin letter. Switch to a Korean keyboard, or tap a letter on the keypad below." };
  }
  return { error: "That isn't one of the 40 Hangul letters. Try the keypad below." };
}

export function gradeAnswer(item: QuizItem, variantIndex: number, input: string): Grade {
  const normalized = normalizeGiven(input);
  if ("error" in normalized) return { status: "invalid", message: normalized.error };
  if (normalized.jamo === item.answer) return { status: "correct" };
  const variant = item.variants[variantIndex] ?? item.variants[0];
  return { status: "wrong", given: normalized.jamo, message: explainWrong(item, variant, normalized.jamo) };
}

// Resolve each Korean-word context into the generic shape the quiz UI reads.
for (const item of QUIZ_ITEMS) {
  for (const v of item.variants) {
    if (!v.ko) continue;
    const blank = blankedWord(v.ko);
    if (blank) v.context = { blank, full: fullWord(v.ko), gloss: v.ko.gloss };
  }
}

const SYMBOL_NAME = new Map(HANGUL_SYMBOLS.map((s) => [s.jamo, s.name]));

const AUDIO_SYLLABLE = new Map(HANGUL_SYMBOLS.map((s) => [s.jamo, s.audioSyllable]));

export const HANGUL_QUIZ: QuizDefinition = {
  deck: "symbols",
  languageCode: "ko",
  statsKey: "symbols",
  answerSize: "letter",
  // A lone jamo is read by its name, so play the representative syllable (ㄱ -> 가), as the flashcards do.
  audioSrc: (item) => {
    const text = AUDIO_SYLLABLE.get(item.answer);
    return text ? `/api/tts?lang=ko&text=${encodeURIComponent(text)}` : null;
  },
  title: "Symbols quiz",
  intro:
    "You'll see an English word with the sound in bold, plus its phonetic code. Write the Hangul letter for that sound - the same letter can sound different at the start and the end of a syllable, so each position gets its own question.",
  defaultPrompt: DEFAULT_PROMPT,
  placeholder: "ㅎ",
  inputLang: "ko",
  contextLabel: "In the Korean word",
  items: QUIZ_ITEMS,
  groups: [POSITION_LABEL.initial, POSITION_LABEL.medial, POSITION_LABEL.final, POSITION_LABEL.vowel],
  itemById,
  variantCode,
  grade: (item, variantIndex, input) => gradeAnswer(item as QuizItem, variantIndex, input),
  answerLabel: (item) => SYMBOL_NAME.get(item.answer) ?? null,
};
